vich_uploader:
    db_driver: orm



    mappings:
        products:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        services:
            uri_prefix: /images/services
            upload_destination: '%kernel.project_dir%/public/images/services'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        diplomes:
            uri_prefix: /images/diplomes
            upload_destination: '%kernel.project_dir%/public/images/diplomes'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true